/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerificationEmailRouteImport } from './routes/verification.$email'
import { Route as _logRegisterRouteImport } from './routes/__log/register'
import { Route as _logLoginRouteImport } from './routes/__log/login'
import { Route as _logForgotPasswordRouteImport } from './routes/__log/forgot-password'

const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationEmailRoute = VerificationEmailRouteImport.update({
  id: '/verification/$email',
  path: '/verification/$email',
  getParentRoute: () => rootRouteImport,
} as any)
const _logRegisterRoute = _logRegisterRouteImport.update({
  id: '/__log/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const _logLoginRoute = _logLoginRouteImport.update({
  id: '/__log/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _logForgotPasswordRoute = _logForgotPasswordRouteImport.update({
  id: '/__log/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof _logForgotPasswordRoute
  '/login': typeof _logLoginRoute
  '/register': typeof _logRegisterRoute
  '/verification/$email': typeof VerificationEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof _logForgotPasswordRoute
  '/login': typeof _logLoginRoute
  '/register': typeof _logRegisterRoute
  '/verification/$email': typeof VerificationEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__auth': typeof _authRouteRoute
  '/__log/forgot-password': typeof _logForgotPasswordRoute
  '/__log/login': typeof _logLoginRoute
  '/__log/register': typeof _logRegisterRoute
  '/verification/$email': typeof VerificationEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verification/$email'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forgot-password' | '/login' | '/register' | '/verification/$email'
  id:
    | '__root__'
    | '/'
    | '/__auth'
    | '/__log/forgot-password'
    | '/__log/login'
    | '/__log/register'
    | '/verification/$email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authRouteRoute: typeof _authRouteRoute
  _logForgotPasswordRoute: typeof _logForgotPasswordRoute
  _logLoginRoute: typeof _logLoginRoute
  _logRegisterRoute: typeof _logRegisterRoute
  VerificationEmailRoute: typeof VerificationEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification/$email': {
      id: '/verification/$email'
      path: '/verification/$email'
      fullPath: '/verification/$email'
      preLoaderRoute: typeof VerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__log/register': {
      id: '/__log/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof _logRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__log/login': {
      id: '/__log/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _logLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__log/forgot-password': {
      id: '/__log/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _logForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authRouteRoute: _authRouteRoute,
  _logForgotPasswordRoute: _logForgotPasswordRoute,
  _logLoginRoute: _logLoginRoute,
  _logRegisterRoute: _logRegisterRoute,
  VerificationEmailRoute: VerificationEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
